Progress as of 05/28/2021

diff --git a/linstrap b/linstrap
--- a/linstrap
+++ b/linstrap
@@ -17,7 +17,7 @@
 ##############################################################################
 
 if [ "$0" == "*bash" ]; then
-    /usr/bin/env -S bash
+    /usr/bin/env -S bash `realpath $0`
     return $?
 fi
 
@@ -115,7 +115,7 @@ else
     LINSTRAP_HOME="`pwd -P`"
     cd "$SAVED" >/dev/null
 
-    VERIFY_MSG="The Linstrap home directory was auto detected as:\n\"$LINSTRAP_HOME\"\nPlease verify that the script is located in the root directory\nor you can manually set the directory with the LINSTRAP_HOME veriable."
+    VERIFY_MSG="The Linstrap home directory was auto detected as:\n\"$LINSTRAP_HOME\"\nPlease verify that the script is located in the real root directory\nor you can manually set the directory with the LINSTRAP_HOME veriable."
 fi
 
 [ -d "$LINSTRAP_HOME" ] || error "The Linstrap home directory does not exist!\n\n$VERIFY_MSG"
@@ -179,17 +179,11 @@ if [ -n "$JAVA_HOME" ] ; then
         JAVACMD="$JAVA_HOME/bin/java"
     fi
     if [ ! -x "$JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
+        error "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
     fi
 else
     JAVACMD="java"
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
+    which java >/dev/null 2>&1 || error "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
 fi
 
 # Increase the maximum file descriptors if we can.
@@ -258,6 +252,8 @@ if $cygwin ; then
     esac
 fi
 
+install -d cache
+
 # Escape application args
 save () {
     for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
@@ -266,7 +262,7 @@ save () {
 APP_ARGS=$(save "$@")
 
 # Collect all arguments for the java command, following the shell quoting and substitution rules
-eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"
+eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain --project-dir "\"$LINSTRAP_HOME\"" --settings-file "\"$LINSTRAP_HOME/scripts/settings.gradle\"" --build-file "\"$LINSTRAP_HOME/scripts/linstrap.gradle\"" "$APP_ARGS"
 
 # by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
 if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
